# Generated by Django 5.1.4 on 2024-12-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(default='E_Silab', max_length=150, verbose_name='nombre')),
                ('pass_user', models.CharField(max_length=100, verbose_name='codigo')),
                ('rol_user', models.CharField(default='null', max_length=100, verbose_name='rol del usuario')),
            ],
        ),
    ]
